### PR TITLE
Overview

### LINKED ISSUE #182: Needs an overview page
https://canjs.com/doc/can-util.html

is pretty blank.

### PR DESCRIPTION
**Pull request by rlin415**
This closes #182 

screen shot 2017-03-05 at 9 49 51 am
screen shot 2017-03-05 at 9 50 18 am

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Should we be showing the module name?  `base-url` instead of `baseUrl`?

**Comment by chasenlehara** [comment]
I would want to get this merged in as-is, but I wonder if it’d be good to create a `bit-docs` tag that can automatically generate an index like this? I could see us using it for pages like [`can-types`](https://canjs.com/doc/can-types.html).

**Comment by justinbmeyer** [comment]
@chasenlehara We had something similar (the @api tag) in DocumentJS.  It probably wouldn't be difficult to re-create.

Why merge before we've figured out if it should be `base-url` instead of `baseUrl`?

**Comment by rlin415** [comment]
You're right. The names should be delimiter-separated instead of camel cased. I'll make the changes.

**Comment by chasenlehara** [comment]
@justinbmeyer Sorry I phrased that poorly; I meant to say I wouldn’t want to delay figuring out a technical solution (like implementing `@api`) before getting this merged in, not that I think it should be merged in with errors.

**Review by chasenlehara — APPROVED** [review]

**Pull request merged**
