### PR TITLE
Add support to abort a promise returned from ajax() call

### PR DESCRIPTION
**Pull request by prashantsharmain**

### CODE REVIEW

**Comment by prashantsharmain** [comment]
@bmomberger-bitovi @justinbmeyer Could you review and let me know if this looks good? Thanks.

**Comment by bmomberger-bitovi** [comment]
Please also update the docs on https://github.com/canjs/can-util/blob/master/dom/ajax/ajax.js#L9 to describe the return value as an "abortable promise" -- has an `.abort()` method (which rejects the promise indirectly), but otherwise is a promise.

**Comment by prashantsharmain** [comment]
@bmomberger-bitovi @justinbmeyer Updated the docs. Please review and see if this can be merged in now.

**Comment by prashantsharmain** [comment]
@bmomberger-bitovi @justinbmeyer Just checking if the updated PR is good to be merged in.

**Comment by bmomberger-bitovi** [comment]
Yes, it's good to go.  I added a thumbs-up to the original description but that may have been too subtle.

**Comment by prashantsharmain** [comment]
@bmomberger-bitovi Thanks !

**Comment by rjgotten** [comment]
> @bmomberger-bitovi
> Yes, it's good to go.

Eh?

This doesn't cover promises being chained via `promise.then()`, `Promise.all()` etc. Not very useful, as there are probably cases within the CanJS framework where promises are chained via `then` and the `abort` method should remain exposed.

Moreover, this plays fast and loose with the fact that Promise instances are extensible.
If the native Promise ever _does_ get extended with an `abort` method that may be troublesome. Either the native method gets clobbered (and then magically gets 'unclobbered' when chained via `then`) or an attempt to set a different value for the abort property outright raises an exception causing code to halt.

Now; this is fairly unlikely as the concept of an abort method for cancellable promises are pretty much out the window in favor of cancellation tokens, but you should also consider the fact that not all browsers have the native Promise implemented and thus authors require a polyfill. And there are plenty that play fast and loose by offering the native API extended with a few extras.

---

Actually, related to polyfills: there's a problem with the way CanJS pulls in promises in general. It assumes `Promise` is available globally. That's a no-no. The proper, isolated way to polyfill such a feature is via a module that passes through the native implementation if it exists and loads the polyfill _as an isolated module that does not pollute global state_ otherwise. CanJS doesn't support that and **forces** authors to do it 'the dirty way'.

That's bad. It goes squarely against the mantra of helping your users to "fall into the pit of success".

As such, CanJS should implement a `can/util/promise` that passes out the native implementation and (in non-production builds) prints a console warning in browsers that don't implement it. The documentation should refer to this and explain that authors should use the module remapping capabilities of their module loader of choice to redirect this module to their full-fledged polyfill of choice.

**Comment by matthewp** [comment]
Bringing in a polyfill adds weight to every browser, even those that don't need it. You can't dynamically import the polyfill, it needs to be a static dependency.  Personally I don't think it's adding a lot to ask a user to provide their own polyfill, it's not difficult.

I do agree about this change being not-ideal due to not being able to chain the promise and still keeping the `abort()` method though.

**Comment by justinbmeyer** [comment]
Yes, this isn't a great solution as acknowledged in the comments above. But it enables to build in better ones if need be. 

Without conditional loading supported by most module systems, I'm wary of packing a Promise polyfill for all our users. Solutions that use module mapping might work, but would be different everywhere. 

Similar to what 2.0 required with HTML5shiv, I think making people polyfill their environment is the most straightforward solution.

**Comment by rjgotten** [comment]
> Without conditional loading supported by most module systems, I'm wary of packing a Promise polyfill for all our users. Solutions that use module mapping might work, but would be different everywhere.

That's the beauty; a default `can/util/promise` module _would_ simply look for `window.Promise` and pass it through, including any from a polyfilled environment.

However, _having_ that module also enables authors that do not want (or cannot) pollute the global scope to use module remapping and inject their own polyfill.

> @matthewp 
> You can't dynamically import the polyfill, it needs to be a static dependency.

Actually; that depends on your loader. Most do support plugins that hook into the loading pipeline and which allow you to write conditional loading logic. ;-)

(This is also why loading the polyfill should still be something that is left to individual authors.)

**Comment by justinbmeyer** [comment]
@rjgotten When I was saying:

> Without conditional loading supported by most module systems

It's similar to what you are talking about here:

> Most do support plugins that hook into the loading pipeline and which allow you to write conditional loading logic.

The problem is that there's no standard way of doing this.

However, I don't think it's that bad of an idea to have a sort of `can-util/natives/promise`.  But if we do it for promises, we should probably do it for the `document` as well.

**Comment by rjgotten** [comment]
Doing it for `document` as well would possibly simplify a few things for unit tests in non-browser environments, no?

**Comment by justinbmeyer** [comment]
@rjgotten yes, it will allow people to map that module to something that provides a document, like `can-simple-dom`.

**Pull request merged**
