### PR TITLE
timing issue with waiting for mutation observers

### PR DESCRIPTION
**Pull request by justinbmeyer**

### CODE REVIEW

**Comment by matthewp** [comment]
Probably a more accurate way to handle this sort of thing would be to set up a new MO (on the documentElement probably) and then perform your checks when that fires. It should run after the code that calls to clean the data.

**Comment by justinbmeyer** [comment]
@matthewp I thought about that, but didn't want to assume mutation observers.  Perhaps someday this works with weak-maps.

**Comment by matthewp** [comment]
You could create a little helper function that uses MO or does a setTimeout(fn, 0) otherwise. If there aren't MOs the events would have happened synchronously.  Probably a good thing to have in can-util since there are similar "wait for events that will happen on the next MO" types of things.

Anyways, no reason to hold up this pr over it, I just wanted to bring up the idea.

**Comment by justinbmeyer** [comment]
if there aren't MOs, we'd be relying on GC which is non-deterministic.

**Pull request merged**
