### PR TITLE
moving dispatch to domEvents

### PR DESCRIPTION
**Pull request by phillipskevin**
First part of fixing can-stache-bindings tests for https://github.com/canjs/canjs/issues/2527.

### CODE REVIEW

**Comment by matthewp** [comment]
What is the reason why it needs to be moved?

**Comment by phillipskevin** [comment]
With dispatch as part of `domEvents`, can-jquery can overwrite it to use `$.trigger`. This is needed so that we can handle extraParameters like this: https://github.com/canjs/can-stache-bindings/blob/master/test/bindings-test.js#L368-L369.

**Comment by matthewp** [comment]
This is tested here: https://github.com/canjs/can-jquery/blob/master/can-jquery_test.js#L159-L180

Is that test wrong?

**Comment by matthewp** [comment]
Oops, closed by mistake, sorry.

**Comment by phillipskevin** [comment]
That test is correct, but it is using `$.trigger` directly. I'm trying to make the same thing work when using `canEvent.trigger`.

**Pull request merged**
